Factorize job setup
Remove redudant job names

Names are useful when they describe what is done in a more concise way than
the code.

Signed-off-by: Gaëtan Lehmann <gaetan.lehmann@vates.tech>

diff --git a/.github/workflows/test-sequences.yml b/.github/workflows/test-sequences.yml
--- a/.github/workflows/test-sequences.yml
+++ b/.github/workflows/test-sequences.yml
@@ -8,23 +8,20 @@ jobs:
   jobs-check:
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v2
-      with:
-        persist-credentials: false
-    - name: Install uv
-      uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba  # v6.3.1
-      with:
-        version: "0.7.x"
-    - name: Install dependencies
-      run: uv sync --frozen --no-dev
-    - name: Create a dummy data.py
-      run: cp data.py-dist data.py
-    - name: jobs-check
-      run: |
-        FAILURES=""
-        for seq in $(find -name "*.lst"); do
-          if ! uv run --no-dev pytest @$seq --collect-only --quiet; then
-            FAILURES="$FAILURES $seq"
-          fi
-        done
-        [ -z "$FAILURES" ] || { echo >&2 "ERROR: test sequences failed consistency check: $FAILURES"; exit 1; }
+      - uses: actions/checkout@v4
+        with:
+          persist-credentials: false
+      - uses: ./.github/actions/uv-setup/
+        with:
+          dev: false
+      - name: Create a dummy data.py
+        run: cp data.py-dist data.py
+      - name: jobs-check
+        run: |
+          FAILURES=""
+          for seq in $(find -name "*.lst"); do
+            if ! pytest @$seq --collect-only --quiet; then
+              FAILURES="$FAILURES $seq"
+            fi
+          done
+          [ -z "$FAILURES" ] || { echo >&2 "ERROR: test sequences failed consistency check: $FAILURES"; exit 1; }
